version: "3.8"

services:

  mongodb:
    image: mongo:7
    container_name: app_mongodb

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    restart: always

  backend:
    build: ./backend

    container_name: app_backend

    environment:
      MONGO_URI: mongodb://admin:admin123@mongodb:27017

    ports:
      - "5000:5000"

    depends_on:
      - mongodb

    networks:
      - backend_net
      - frontend_net

  frontend:
    build: ./frontend

    container_name: app_frontend

    ports:
      - "80:80"

    depends_on:
      - backend

    networks:
      - frontend_net

volumes:
  mongo_data:

networks:
  backend_net:
    driver: bridge

  frontend_net:
    driver: bridge